# Site settings
title: MUHAMMED JANISH
description: Engineering Student at MESCE
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Muhammed Janish
user_description: "I'd imagine the whole world was one big machine. Machines never come with any extra parts, you know. They always come with the exact amount they need. So I figured, if the entire world was one big machine, I couldn't be an extra part. I had to be here for some reason. And that means you have to be here for some reason, too"
user_title: Engineering Student at MESCE
email: janishumj@gmail.com
twitter_username: lorem_ipsum
github_username: janishumj
gplus_username: janishumj

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
